## Pandas

In [1]:
import pandas as pd
import numpy as np
from numpy import nan

In [2]:
df = pd.read_csv('/content/mtcars.csv')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## loc & iloc

# loc[:,:]
# iloc[:,:]

In [3]:
df.loc[1:3,'model':'hp']

            model   mpg  cyl   disp   hp
1   Mazda RX4 Wag  21.0    6  160.0  110
2      Datsun 710  22.8    4  108.0   93
3  Hornet 4 Drive  21.4    6  258.0  110

In [4]:
df.iloc[1:4,0:5]

            model   mpg  cyl   disp   hp
1   Mazda RX4 Wag  21.0    6  160.0  110
2      Datsun 710  22.8    4  108.0   93
3  Hornet 4 Drive  21.4    6  258.0  110

In [5]:
df.loc[3]

model    Hornet 4 Drive
mpg                21.4
cyl                   6
disp              258.0
hp                  110
drat               3.08
wt                3.215
qsec              19.44
vs                    1
am                    0
gear                  3
carb                  1
Name: 3, dtype: object

In [6]:
df.iloc[3]

model    Hornet 4 Drive
mpg                21.4
cyl                   6
disp              258.0
hp                  110
drat               3.08
wt                3.215
qsec              19.44
vs                    1
am                    0
gear                  3
carb                  1
Name: 3, dtype: object

In [8]:
df.loc[0:4]

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
df.iloc[0:4]

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1

# Encoding

## Converting object to int/float

### Types of encoding:
1. One hot encoding
2. Label encoding
3. Manual Encoding

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [12]:
# One hot encoding
pd.get_dummies(df['model'])

,AMC Javelin,Cadillac Fleetwood,Camaro Z28,Chrysler Imperial,Datsun 710,Dodge Challenger,Duster 360,Ferrari Dino,Fiat 128,Fiat X1-9,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [13]:
d = {'name':['a', 'b', 'c', 'd', 'e'], 'Age':[19,22,18,19,59], 'Gender' : ['M', 'F', 'M', 'M', 'F']}
df3 = pd.DataFrame(d)
df3['Salary'] = [34000, 50000, 45000, 30000, 30000]
df3

  name  Age Gender  Salary
0    a   19      M   34000
1    b   22      F   50000
2    c   18      M   45000
3    d   19      M   30000
4    e   59      F   30000

In [16]:
one_hot = pd.get_dummies(df3['Gender'])
one_hot

   F  M
0  0  1
1  1  0
2  0  1
3  0  1
4  1  0

In [17]:
df4 = df3.join(one_hot)
df4

  name  Age Gender  Salary  F  M
0    a   19      M   34000  0  1
1    b   22      F   50000  1  0
2    c   18      M   45000  0  1
3    d   19      M   30000  0  1
4    e   59      F   30000  1  0

In [19]:
df_enc = pd.get_dummies(df['model'])
df_enc

,AMC Javelin,Cadillac Fleetwood,Camaro Z28,Chrysler Imperial,Datsun 710,Dodge Challenger,Duster 360,Ferrari Dino,Fiat 128,Fiat X1-9,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
df_new = df.join(df_enc)
df_new

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,...,0,0,0,0,0,0,0,0,0,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,...,0,0,0,0,0,0,0,0,0,0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,...,0,0,0,0,0,0,0,0,0,0
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,...,0,0,0,0,0,0,0,0,1,0
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,...,0,0,0,0,0,0,0,0,0,0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,...,0,0,0,0,0,0,0,0,0,0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,...,0,0,0,0,0,0,0,0,0,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,...,1,0,0,0,0,0,0,0,0,0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,...,0,1,0,0,0,0,0,0,0,0
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,...,0,0,1,0,0,0,0,0,0,0
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,...,0,0,0,1,0,0,0,0,0,0
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,...,0,0,0,0,0,0,0,0,0,0
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,...,0,0,0,0,0,0,0,0,0,0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,...,0,0,0,0,0,0,1,0,0,0
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,...,0,0,0,0,0,0,0,1,0,0
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,...,0,0,0,0,0,0,0,0,0,0
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,...,0,0,0,0,1,0,0,0,0,0
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,...,0,0,0,0,0,0,0,0,0,0
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,...,0,0,0,0,0,1,0,0,0,0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,...,0,0,0,0,0,0,0,0,0,0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,...,0,0,0,0,0,0,0,0,0,0
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,...,0,0,0,0,0,0,0,0,0,0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,...,0,0,0,0,0,0,0,0,0,0
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,...,0,0,0,0,0,0,0,0,0,1

# Label Encoder

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [23]:
df3['Gender'] = le.fit_transform(df3['Gender'])
df3

  name  Age  Gender  Salary
0    a   19       1   34000
1    b   22       0   50000
2    c   18       1   45000
3    d   19       1   30000
4    e   59       0   30000

In [24]:
df_trial = df
df_trial.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [25]:
df_trial['model'] = le.fit_transform(df['model'])
df_trial

    model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      17  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      18  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2       4  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      12  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      13  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5      30  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6       6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7      20  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8      19  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9      21  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10     22  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11     23  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12     24  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13     25  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14      1  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15     14  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16      3  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17      8  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18     11  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19     28  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20     29  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21      5  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22      0  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23      2  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     26  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25      9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26     27  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27     15  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28     10  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29      7  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30     16  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31     31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [26]:
df.loc[22]

model      0.000
mpg       15.200
cyl        8.000
disp     304.000
hp       150.000
drat       3.150
wt         3.435
qsec      17.300
vs         0.000
am         0.000
gear       3.000
carb       2.000
Name: 22, dtype: float64

In [27]:
df

    model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      17  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      18  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2       4  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      12  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      13  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5      30  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6       6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7      20  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8      19  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9      21  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10     22  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11     23  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12     24  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13     25  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14      1  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15     14  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16      3  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17      8  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18     11  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19     28  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20     29  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21      5  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22      0  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23      2  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     26  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25      9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26     27  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27     15  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28     10  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29      7  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30     16  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31     31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [28]:
le.inverse_transform([9])

array(['Fiat X1-9'], dtype=object)

In [29]:
le.inverse_transform([0])

array(['AMC Javelin'], dtype=object)